### ISSUE TITLE
There are trojans in this when I download it?

### ISSUE THREAD

**Issue by GitDude82** [CloneTrooper1019/Roblox-2007-Client#16]
When I download this, my computer detects two or three Trojan viruses. I doubt this is happening for anyone else. so I'm confused. Can I get an answer to this?

**Comment by Rahib777-7** [comment]
Ofc its not a virus its a false positive

**Comment by GitDude82** [comment]
No. It detects the Oneeva virus. An ACTUAL TROJAN made to harm your computer.

**Comment by CloneTrooper1019** [comment]
@GitDude82 It’s a false positive. The reason it’s picking up that is because the application was never signed by Roblox, so the antivirus machine learning vendors coincidentally happened to find some behavior that partially resembles whatever that Trojan is. $10 says it’s mad because the executable writes files and makes registry key changes to its own sandboxed keys and nothing else. I’m submitting the executable for analysis soon so hopefully this will be cleared up.
