### ISSUE TITLE
My PC thinks this is a virus

### ISSUE THREAD

**Issue by iamre** [CloneTrooper1019/Roblox-2007-Client#17]
what can i do to fix it

**Comment by DuckZGamer9122** [comment]
Hi.
I am not a developer but I can assure you it is a false positive. 
Clonetrooper doesn't put malicious code in any of his work.

**Comment by CloneTrooper1019** [comment]
It’s a false positive. The reason it’s picking up that is because the application was never signed by Roblox, so the antivirus machine learning vendors coincidentally happened to find some behavior that partially resembles whatever that Trojan is. $10 says it’s mad because the executable writes files and makes registry key changes to its own sandboxed keys and nothing else. I’m submitting the executable for analysis soon so hopefully this will be cleared up.
